### ISSUE TITLE
freeList not work

### ISSUE THREAD

**Issue by provalinf** [frosqh/GRAFLib#3]
Il me semble que le freelist ne fonctionne pas :
1. importer graph testFile
2. supprimer le graph
3. réimporter
segfault

Ou au lieu d'en réimporter un, createGraph, puis addNode (là noeud déjà existant) via le débogueur les noeuds du précédent graph sont encore visibles

**Comment by frosqh** [comment]
@provalinf J'ai vraiment aucune idée de ce qui déclenche le bug. En passant tout en pointeur et en rajoutant un free(g) dans deleteGraph, le segfault ne se produit plus à l'import mais lorsqu'on essaye d'afficher le graph.

**Comment by provalinf** [comment]
ok ça marche, j'avais pas d'idée non plus de toute façon

**Comment by provalinf** [comment]
Bon je dépose la version avec ton dernier commit tel quel, si tu veux encore modifier avant l'heure, fait moi signe.
